# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 38bdef535a3ad790ca6a203d34548ce98e9411b6b2beec6ef67586d225dbc6dd6822740304c012cdfd59e976ca2d13ebaadde10fb3c003214e5a9b8a39971756

test:
  secret_key_base: fd103a5a9673a0682792c605b34ff6e0ccb82aad3f564e13f97f15213ee374ba79490982f44a94b2680532642383791192266ff7bf05284f7e4ad9fb52800194

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
